nav:
  - PSGSuite: index.md
  - Installation:
    - Overview: pages/installation/overview.md
    - Powershell Gallery: pages/installation/powershell_gallery.md
    - GitHub Releases: pages/installation/github_releases.md
    - Building From Source: pages/installation/building_from_source.md
  - First Time Configuration:
    - Google Cloud: pages/first_time_configuration/google_cloud_configuration.md
    - Module Configuration: pages/first_time_configuration/module_configuration.md
  - Examples: pages/examples
  - Function Help: pages/function_help
append_unmatched: true
